### ISSUE TITLE
我尝试训练cenet，为什么训练结果比论文中低了很多呢

### ISSUE THREAD

**Issue by NaiveN00b** [LiaoMengqi/KGTL#3]
我先是用readme里训练cenet的命令后来把early-stop调大，都差不多，结果差的非常多，这是为什么呢？

**Comment by LiaoMengqi** [comment]
本方法库适合用于学习，实现的方法在细节层面和论文会有一定差别，不能保证性能一致。此外超参数的选择对模型性能也会有很大影响。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月15日(周一) 下午5:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [LiaoMengqi/KGMH] 我尝试训练cenet，为什么训练结果比论文中低了很多呢 (Issue #3)




 
Closed #3 as completed.

**Comment by NaiveN00b** [comment]
@LiaoMengqi 我看到你知乎上的一篇文章了，是因为你使用的过滤方式不太一样hh
